### PR TITLE
Wrap the open-browser-to function in future function

### PR DESCRIPTION
**Pull request by ayato0211**
this function never finished when user didn't opend system-default browser.

### CODE REVIEW

**Comment by weavejester** [comment]
Wrapping a function that hangs in a future isn't a solution; it still results in a blocked thread.

**Comment by ayato0211** [comment]
I see, I will close this PR now.

Could you please solve this issue ?

**Comment by weavejester** [comment]
You haven't explained what the issue is in any detail, and it sounds as if the problem isn't with ring-server, but a problem with `clojure.java.browse/browse-url` on your system.

**Comment by ayato0211** [comment]
Sorry, for that.
I will explain about my situation.
I'm using Linux OS(ubuntu), cider-mode and this library with Clojure 0.6.
When developing some web application, I tried to start the server in the REPL then I noticed start-server function will never finished sometimes.
I said "sometimes", but I found the cause of why start-server never finished. So that is open-browser? option is true and system- browser not yet opened case.
Even if any other OS will works, this problem from clojure.java.browse/browse-url on my system as you say.
Thanks.

**Pull request closed without merging**
